name: Build and Release APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2

    - name: Accept Android licenses
      run: |
        yes | sdkmanager --licenses || true

    - name: Get current date
      id: date
      run: echo "date=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_OUTPUT

    - name: Debug file structure
      run: ls -laR
      
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build Release APK
      run: ./gradlew assembleRelease --stacktrace

    - name: Prepare APKs
      run: |
        mkdir -p apk-artifacts
        find . -name '*.apk' -exec cp {} apk-artifacts/ \;
        ls -la apk-artifacts

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: AutoTapApp
        path: apk-artifacts/*.apk
        retention-days: 1

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: auto-release-${{ github.run_id }}
        name: AutoTapApp Release ${{ github.run_number }}
        body: |
          APK for AutoTap Accessibility Service
          - 自动点击"立即开始"按钮
          - 构建时间: ${{ steps.date.outputs.date }}
          - 触发提交: ${{ github.sha }}
        draft: false
        prerelease: false
        files: apk-artifacts/*.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
